name: "Docker image"

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        id: secrets
        with:
          url: https://vault.afdevops.com
          method: jwt
          role: jwt-github-role
          path: jwt-github
          jwtGithubAudience: https://github.com/AnchorFree
          secrets: |
            secret/devops/cloud_providers/gcp/aura-networking/gar/gh-actions-rw auth | REGISTRY_PASSWORD;

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ steps.secrets.outputs.REGISTRY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            us-docker.pkg.dev/aura-networking/docker-registry/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
